---
build_from:
  aarch64: ghcr.io/hassio-addons/base:17.0.0
  amd64: ghcr.io/hassio-addons/base:17.0.0
  armv7: ghcr.io/hassio-addons/base:17.0.0
codenotary:
  base_image: notary@home-assistant.io
  signer: andrewjswan@addons.community
