---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.5
  amd64: ghcr.io/hassio-addons/base:16.3.5
  armv7: ghcr.io/hassio-addons/base:16.3.5
codenotary:
  base_image: notary@home-assistant.io
  signer: andrewjswan@addons.community
